version: '3'

services:
  web1:
    build: ./flask
    ports:
      - "8080:8080"

  web2:
    build: ./flask
    ports:
      - "8081:8080"

  web3:
    build: ./flask
    ports:
      - "8082:8080"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2
      - web3


